# SmellSense (https://dart.dev/tools/pub/pubspec)

name: smellsense
description: A mobile application for smell training.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

# Versions and builds
# Android: https://developer.android.com/studio/publish/versioning
# iOS: https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+10

# Flutter SDK
environment:
  sdk: ">=3.4.3 <4.0.0"

# Application dependencies
dependencies:
  flutter:
    sdk: flutter

  # TODO: Add localizations
  flutter_localizations:
    sdk: flutter

  get_it: ^7.7.0
  google_fonts: 6.2.1
  path_provider: ^2.1.3
  im_stepper: 1.0.1+1
  circular_countdown_timer: ^0.2.3
  hive: ^2.2.3
  hive_flutter: 1.1.0
  fluttertoast: ^8.2.6
  flutter_screenutil: ^5.9.3
  url_launcher: ^6.3.0
  flutter_svg: 2.0.10+1
  flutter_widget_from_html: 0.15.1
  fl_chart: ^0.68.0
  floor: ^1.5.0
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  go_router: ^14.2.0
  provider: ^6.1.2
  flutter_rating_bar: ^4.0.1
  json_annotation: ^4.9.0
  sqflite: any
  logger: ^2.4.0
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.1.11
  floor_generator: ^1.5.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  husky: ^0.1.7
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.25.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  # Resolution-aware assets: https://flutter.dev/assets-and-#resolution-aware.s
  assets:
    # Icons

    ## App icons
    - assets/icons/smellsense_logo.svg

    # Images

    ## Supported scents
    - assets/images/chamomile.png
    - assets/images/cinnamon.png
    - assets/images/citronella.png
    - assets/images/clove.png
    - assets/images/eucalyptus.png
    - assets/images/garlic.png
    - assets/images/grapefruit.png
    - assets/images/lavender.png
    - assets/images/lemon.png
    - assets/images/mint.png
    - assets/images/orange.png
    - assets/images/rose.png
    - assets/images/rosemary.png
    - assets/images/teatree.png

    # Parosmia smell reaction emojis
    - assets/icons/reactions/angry.svg
    - assets/icons/reactions/disgusted.svg
    - assets/icons/reactions/unhappy.svg
    - assets/icons/reactions/neutral.svg
    - assets/icons/reactions/pleased.svg
    - assets/icons/reactions/happy.svg
